notifications:
  email: false

sudo: false

addons:
  postgresql: 9.3

services:
  - redis
  - postgresql

language: python

matrix:
  fast_finish: true

cache:
  - pip

env:
env:
  - REQUIREMENTS=lowest ES_HOST=127.0.0.1 ES_VERSION=2.2.0 SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
  - REQUIREMENTS=release ES_HOST=127.0.0.1 ES_VERSION=2.2.0 SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
  - REQUIREMENTS=devel ES_HOST=127.0.0.1 ES_VERSION=2.2.0 SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"

python:
  - '2.7'
  - '3.5'

before_install:
  - "mkdir /tmp/elasticsearch"
  - "wget -O - https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1"
  - "/tmp/elasticsearch/bin/plugin install mapper-attachments -b"
  - "/tmp/elasticsearch/bin/elasticsearch &"
  - "sleep 20"
  - travis_retry pip install --upgrade pip setuptools py
  - travis_retry pip install twine wheel coveralls requirements-builder
  - requirements-builder --level=min setup.py > .travis-lowest-requirements.txt
  - requirements-builder --level=pypi setup.py > .travis-release-requirements.txt
  - requirements-builder --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt

install:
  - travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt
  - travis_retry pip install -e .[all]

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: inveniosoftware
  password:
    secure: "N5j7zEaZzUgpwnBFp8zqGEXtMsVELen0ChD8baOUubZAUtXcqrqcVoveDQTGrd0bBcMPJhDYGltnApAb1OC2Be03xsQABX5iDZ1uPRoffFkHCSR3Y1qwe9HhStKhjaEvw7hPhKDKaWPEMBqowLfCpLSw84zDsUeVnJDxt1KKuh89PS1dPlUWS1KAjmYdoYMDz0GUQ8e3IlUhrb2sA2DsITtTXpXZ24d7HfRM5mjZciA6x2lnIgxI0d2MYY4ZyC242f7a0H0dJM0LfG2m3cH2sDfGnTiNuN9Oimrqsehc7LXfrypkK40r+v9WLGMvBnhV+yqH7fbGL6CjV/eNL1KoK+vrPmjsAJ6XafnLxIpHdWL6dAl1iBJktWtvtckRXA5SlV8D91oszA1XxI8X49nf1SZzjOmCfEM/T+jaIof7Ol7EeeFRQmcGpn80+RcdKAmcpUGv1BM6p5h0ZZVMEZ+GBe3eST8t6A5gZCtB2SY+2FeIdnvPnRP1mrtxWl/WXOiLHPbXSIYzfyt40E1ZS8urgVPfghoN0QPzgzjPp4j3QgBaHFqHgEBUODU0DmC/ApmlGAzLy+qb8TRV6gAVvw7KYj+LY0pSX3dExWoXPTAAeDPY5DWZADuyM56qp7dThCPfPUQ53XYzq6Q5Xol35l/KNsYr65iRp2UyMJR4P4bFNyg="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "2.7"
    conditions: $REQUIREMENTS = release
